### ISSUE TITLE
Failed to load scoreboard crash

### ISSUE THREAD

**Issue by mnbvc321** [MCGamerNetwork/Issues#59]
Sometimes when i join a lobby or do /hub it crashes. This has been happening to me for a few weeks now.

This is what it says when it crashes.

---- Minecraft Crash Report ----
// You're mean.

Time: 22/10/14 21:43
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at ayr.k(SourceFile:129)
	at biv.a(SourceFile:1070)
	at hq.a(SourceFile:43)
	at hq.a(SourceFile:9)
	at ef.a(SourceFile:164)
	at biy.e(SourceFile:212)
	at azd.o(SourceFile:1281)
	at azd.ad(SourceFile:753)
	at azd.e(SourceFile:704)
	at net.minecraft.client.main.Main.main(SourceFile:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

**Comment by subv3rsion** [comment]
Just checking in on this, as it looks like there hasn't been any additional comments here. Can you confirm if you still encounter these issues?

**Comment by subv3rsion** [comment]
Without further information, we cannot proceed with this issue. We haven't heard nearly as many issues with the scoreboard, so this may have been resolved as of the latest versions of 1.7, or even as recent as 1.8. If you are still encountering this problem, feel free to let us know and create a new issue.
